linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    disabled-checks:
      - ifElseChain
  godot:
    scope: all
  goimports:
    local-prefixes: gitlab.com/tozd/dinit
  gosimple:
    checks:
      - all
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 170
  nestif:
    min-complexity: 15
  nolintlint:
    allow-unused: false
    require-specific: true
  stylecheck:
    checks:
      - all
  staticcheck:
    checks:
      - all
  tagalign:
    strict: true
  testifylint:
    require-error:
      fn-pattern: ^(NoError|NotErrorIs)$

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
    # - cyclop
    # - depguard
    # - funlen
    # - gci
    # - gocognit
    # - gocyclo
    # - godox
    # - nlreturn
    # - varnamelen
    # - wsl

issues:
  exclude-rules:
    - path: main\.go
      linters:
        - lll
