linters-settings:
  errcheck:
    check-type-assertions: true
    enable-all: true
  gocritic:
    disabled-checks:
      - ifElseChain
  godot:
    scope: all
  gofumpt:
    go: "1.20"
  goimports:
    local-prefixes: gitlab.com/tozd/dinit
  gosimple:
    go: "1.20"
    checks:
      - all
  govet:
    check-shadowing: true
  lll:
    line-length: 170
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
  stylecheck:
    go: "1.20"
    checks:
      - all
  staticcheck:
    go: "1.20"
    checks:
      - all
  unused:
    go: "1.20"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    # - bodyclose
    # - goerr113
    # - nosprintfhostport
    # - wrapcheck
    # - zerologlint

issues:
  exclude-rules:
    - path: main\.go
      linters:
        - lll
